[mgr]
cwd = { fg = "#27a1b9" }
# Count
count_copied = { fg = "black", bg = "green" }
count_cut = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }
# Border
border_symbol = "â”‚"
border_style = { fg = "#181a22" }

[tabs]
active = { fg = "#24273a", bg = "#8aadf4", bold = true }
inactive = { fg = "#8aadf4", bg = "#363a4f" }

[mode]
normal_main = { bg = "blue", fg = "black", bold = true }
normal_alt = { bg = "#181a22", fg = "blue", bold = true }
select_main = { bg = "yellow", fg = "black", bold = true }
select_alt = { bg = "#181a22", fg = "blue", bold = true }
unset_main = { bg = "red", fg = "black", bold = true }
unset_alt = { bg = "#181a22", fg = "blue", bold = true }

[help]
hovered = { bg = "#181a22", bold = true }
footer = { fg = "gray", bg = "black" }
